/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'template adapter settings': {
        'en': 'Adapter settings for template',
        'de': 'Adaptereinstellungen für template',
        'ru': 'Настройки адаптера для template',
        'pt': 'Configurações do adaptador para template',
        'nl': 'Adapterinstellingen voor template',
        'fr': "Paramètres d'adaptateur pour template",
        'it': "Impostazioni dell'adattatore per template",
        'es': 'Ajustes del adaptador para template',
        'pl': 'Ustawienia adaptera dla template',
        'zh-cn': 'template的适配器设置'
    },
	"Scan cameras": {
    "en": "Scan cameras",
    "de": "Kameras scannen",
    "ru": "Поиск камер",
    "pt": "Digitalizar câmeras",
    "nl": "Camera's scannen",
    "fr": "Caméras à balayage",
    "it": "Scansione di telecamere",
    "es": "Escanear cámaras",
    "pl": "Skanuj kamery",
    "zh-cn": "扫描相机"
  },
  "Start range": {
    "en": "Start range",
    "de": "Startbereich",
    "ru": "Начало диапазона",
    "pt": "Intervalo inicial",
    "nl": "Startbereik",
    "fr": "Gamme de départ",
    "it": "Inizia gamma",
    "es": "Rango de inicio",
    "pl": "Zakres początkowy",
    "zh-cn": "起始范围"
  },
  "End range": {
    "en": "End range",
    "de": "Endbereich",
    "ru": "Конец диапазона",
    "pt": "Intervalo final",
    "nl": "Einde bereik",
    "fr": "Gamme finale",
    "it": "Fine gamma",
    "es": "Rango final",
    "pl": "Zakres końcowy",
    "zh-cn": "终点范围"
  },
  "Port list": {
    "en": "Port list",
    "de": "Portliste",
    "ru": "Список портов",
    "pt": "Lista de portas",
    "nl": "Port lijst",
    "fr": "Liste des ports",
    "it": "Elenco delle porte",
    "es": "Lista de puertos",
    "pl": "Lista portów",
    "zh-cn": "端口列表"
  },
  "User name": {
    "en": "User name",
    "de": "Nutzername",
    "ru": "Имя пользователя",
    "pt": "Nome do usuário",
    "nl": "Gebruikersnaam",
    "fr": "Nom d'utilisateur",
    "it": "Nome utente",
    "es": "Nombre de usuario",
    "pl": "Nazwa Użytkownika",
    "zh-cn": "用户名"
  },
  "Password": {
    "en": "Password",
    "de": "Passwort",
    "ru": "Пароль",
    "pt": "Senha",
    "nl": "Wachtwoord",
    "fr": "Mot de passe",
    "it": "Parola d'ordine",
    "es": "Contraseña",
    "pl": "Hasło",
    "zh-cn": "密码"
  },
  "Start scan": {
    "en": "Start scan",
    "de": "Scan starten",
    "ru": "Начать сканирование",
    "pt": "Inicia escaneamento",
    "nl": "Start scan",
    "fr": "Lancer l'analyse",
    "it": "Inizia scansione",
    "es": "Iniciar escaneo",
    "pl": "Rozpocznij skanowanie",
    "zh-cn": "开始扫描"
  },
  "Cancel": {
    "en": "Cancel",
    "de": "Stornieren",
    "ru": "Отмена",
    "pt": "Cancelar",
    "nl": "Annuleer",
    "fr": "Annuler",
    "it": "Annulla",
    "es": "Cancelar",
    "pl": "anulować",
    "zh-cn": "取消"
  },
  "Add camera": {
    "en": "Add camera",
    "de": "Kamera hinzufügen",
    "ru": "Добавить камеру",
    "pt": "Adicionar câmera",
    "nl": "Camera toevoegen",
    "fr": "Ajouter une caméra",
    "it": "Aggiungi fotocamera",
    "es": "Agregar cámara",
    "pl": "Dodaj kamerę",
    "zh-cn": "新增相机"
  },
  "Yes": {
    "en": "Yes",
    "de": "Ja",
    "ru": "Да",
    "pt": "sim",
    "nl": "Ja",
    "fr": "Oui",
    "it": "sì",
    "es": "si",
    "pl": "tak",
    "zh-cn": "是"
  },
  "Port": {
    "en": "Port",
    "de": "Hafen",
    "ru": "Порт",
    "pt": "Porta",
    "nl": "Haven",
    "fr": "Port",
    "it": "Porta",
    "es": "Puerto",
    "pl": "Port",
    "zh-cn": "港口"
  },
  "IP": {
    "en": "IP",
    "de": "IP",
    "ru": "IP",
    "pt": "IP",
    "nl": "IK P",
    "fr": "IP",
    "it": "IP",
    "es": "IP",
    "pl": "IP",
    "zh-cn": "知识产权"
  },
  "Confirm deletion": {
    "en": "Confirm deletion",
    "de": "Löschung bestätigen",
    "ru": "Подтвердить удаление",
    "pt": "Confirmar exclusão",
    "nl": "Bevestig verwijdering",
    "fr": "Confirmer la suppression",
    "it": "Confermare la cancellazione",
    "es": "Confirmar la eliminación",
    "pl": "Potwierdź usunięcie",
    "zh-cn": "确认删除"
  },
  "Do you really whant to delete device?": {
    "en": "Do you really whant to delete device?",
    "de": "Möchten Sie das Gerät wirklich löschen?",
    "ru": "Вы действительно хотите удалить устройство?",
    "pt": "Você realmente deseja excluir o dispositivo?",
    "nl": "Wilt u het apparaat echt verwijderen?",
    "fr": "Voulez-vous vraiment supprimer l'appareil?",
    "it": "Vuoi davvero cancellare il dispositivo?",
    "es": "¿Realmente quieres eliminar el dispositivo?",
    "pl": "Czy naprawdę chcesz usunąć urządzenie?",
    "zh-cn": "您真的想删除设备吗？"
  }
};