/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Onvif adapter settings': {
        'en': 'Adapter settings for Onvif',
        'de': 'Adaptereinstellungen für Onvif',
        'ru': 'Настройки адаптера для Onvif',
        'pt': 'Configurações do adaptador para Onvif',
        'nl': 'Adapterinstellingen voor Onvif',
        'fr': "Paramètres d'adaptateur pour Onvif",
        'it': "Impostazioni dell'adattatore per Onvif",
        'es': 'Ajustes del adaptador para Onvif',
        'pl': 'Ustawienia adaptera dla Onvif',
        'zh-cn': 'template的适配器设置'
    },
	"Scan cameras": {
    "en": "Scan cameras",
    "de": "Kameras scannen",
    "ru": "Поиск камер",
    "pt": "Digitalizar câmeras",
    "nl": "Camera's scannen",
    "fr": "Caméras à balayage",
    "it": "Scansione di telecamere",
    "es": "Escanear cámaras",
    "pl": "Skanuj kamery",
    "zh-cn": "扫描相机"
  },
  "start_range": {
    "en": "Start range",
    "de": "Startbereich",
    "ru": "Начало диапазона",
    "pt": "Intervalo inicial",
    "nl": "Startbereik",
    "fr": "Gamme de départ",
    "it": "Inizia gamma",
    "es": "Rango de inicio",
    "pl": "Zakres początkowy",
    "zh-cn": "起始范围"
  },
  "end_range": {
    "en": "End range",
    "de": "Endbereich",
    "ru": "Конец диапазона",
    "pt": "Intervalo final",
    "nl": "Einde bereik",
    "fr": "Gamme finale",
    "it": "Fine gamma",
    "es": "Rango final",
    "pl": "Zakres końcowy",
    "zh-cn": "终点范围"
  },
  "ports": {
    "en": "Port list",
    "de": "Portliste",
    "ru": "Список портов",
    "pt": "Lista de portas",
    "nl": "Port lijst",
    "fr": "Liste des ports",
    "it": "Elenco delle porte",
    "es": "Lista de puertos",
    "pl": "Lista portów",
    "zh-cn": "端口列表"
  },
  "user": {
    "en": "User name",
    "de": "Nutzername",
    "ru": "Имя пользователя",
    "pt": "Nome do usuário",
    "nl": "Gebruikersnaam",
    "fr": "Nom d'utilisateur",
    "it": "Nome utente",
    "es": "Nombre de usuario",
    "pl": "Nazwa Użytkownika",
    "zh-cn": "用户名"
  },
  "pass": {
    "en": "Password",
    "de": "Passwort",
    "ru": "Пароль",
    "pt": "Senha",
    "nl": "Wachtwoord",
    "fr": "Mot de passe",
    "it": "Parola d'ordine",
    "es": "Contraseña",
    "pl": "Hasło",
    "zh-cn": "密码"
  },
  "Start scan": {
    "en": "Start scan",
    "de": "Scan starten",
    "ru": "Начать сканирование",
    "pt": "Inicia escaneamento",
    "nl": "Start scan",
    "fr": "Lancer l'analyse",
    "it": "Inizia scansione",
    "es": "Iniciar escaneo",
    "pl": "Rozpocznij skanowanie",
    "zh-cn": "开始扫描"
  },
  "Cancel": {
    "en": "Cancel",
    "de": "Stornieren",
    "ru": "Отмена",
    "pt": "Cancelar",
    "nl": "Annuleer",
    "fr": "Annuler",
    "it": "Annulla",
    "es": "Cancelar",
    "pl": "anulować",
    "zh-cn": "取消"
  },
  "yes": {
    "en": "Yes",
    "de": "Ja",
    "ru": "да",
    "pt": "sim",
    "nl": "Ja",
    "fr": "Oui",
    "it": "sì",
    "es": "si",
    "pl": "tak",
    "zh-cn": "是"
  },
  "Confirm deletion": {
    "en": "Confirm deletion",
    "de": "Löschung bestätigen",
    "ru": "Подтвердить удаление",
    "pt": "Confirmar exclusão",
    "nl": "Bevestig verwijdering",
    "fr": "Confirmer la suppression",
    "it": "Confermare la cancellazione",
    "es": "Confirmar la eliminación",
    "pl": "Potwierdź usunięcie",
    "zh-cn": "确认删除"
  },
  "Do you really whant to delete device?": {
    "en": "Do you really whant to delete device?",
    "de": "Möchten Sie das Gerät wirklich löschen?",
    "ru": "Вы действительно хотите удалить устройство?",
    "pt": "Você realmente deseja excluir o dispositivo?",
    "nl": "Wilt u het apparaat echt verwijderen?",
    "fr": "Voulez-vous vraiment supprimer l'appareil?",
    "it": "Vuoi davvero cancellare il dispositivo?",
    "es": "¿Realmente quieres eliminar el dispositivo?",
    "pl": "Czy naprawdę chcesz usunąć urządzenie?",
    "zh-cn": "您真的想删除设备吗？"
  },
  "Settings camera": {
    "en": "Settings camera",
    "de": "Einstellungen Kamera",
    "ru": "Настройки камеры",
    "pt": "Câmera de configurações",
    "nl": "Instellingen camera",
    "fr": "Paramètres caméra",
    "it": "Fotocamera impostazioni",
    "es": "Ajustes de la cámara",
    "pl": "Ustawienia kamery",
    "zh-cn": "设置相机"
  },
  "Camera name": {
    "en": "Camera name",
    "de": "Kameraname",
    "ru": "Название камеры",
    "pt": "Nome da câmera",
    "nl": "Cameranaam",
    "fr": "Nom de la caméra",
    "it": "Nome della telecamera",
    "es": "Nombre de la cámara",
    "pl": "Nazwa kamery",
    "zh-cn": "相机名称"
  },
  "timeout": {
    "en": "Response timeout",
    "de": "Antwortzeitlimit",
    "ru": "Время ожидания ответа",
    "pt": "Tempo limite de resposta",
    "nl": "Time-out van reactie",
    "fr": "Délai de réponse",
    "it": "Timeout di risposta",
    "es": "Tiempo de espera de respuesta",
    "pl": "Limit czasu odpowiedzi",
    "zh-cn": "响应超时"
  },
  "ms": {
    "en": "milliseconds",
    "de": "Millisekunden",
    "ru": "миллисекунды",
    "pt": "milissegundos",
    "nl": "milliseconden",
    "fr": "millisecondes",
    "it": "millisecondi",
    "es": "milisegundos",
    "pl": "milisekundy",
    "zh-cn": "毫秒"
  },
  "subscribeEvents": {
    "en": "subscribe events cameras",
    "de": "Abonnieren Sie Ereigniskameras",
    "ru": "подписаться на события камеры",
    "pt": "assinar eventos câmeras",
    "nl": "abonneren evenementen camera's",
    "fr": "souscrire des caméras d'événements",
    "it": "iscriviti alle telecamere degli eventi",
    "es": "suscribirse cámaras de eventos",
    "pl": "subskrybuj kamery wydarzeń",
    "zh-cn": "订阅活动相机"
  },
  "save": {
    "en": "Save",
    "de": "sparen",
    "ru": "Сохранить",
    "pt": "Salve ",
    "nl": "Opslaan",
    "fr": "sauvegarder",
    "it": "Salva",
    "es": "Salvar",
    "pl": "Zapisać",
    "zh-cn": "保存"
  }
};